name: Deploy to server

on:
  push:
    branches:
      - master

jobs:
  set-up:
    runs-on: ubuntu-latest

    steps:
      - name: setup
        run: echo "setup"

  deploy:
    needs: set-up
    runs-on: ubuntu-latest

    steps:
      - name: Hola Mundo
        run: echo ${{secrets.NAME}}
