name: Deploy to server

on:
  push:
    branches:
      - master

jobs:
  set-up:
    runs-on: ubuntu-latest

    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo"

  deploy:
    needs: set-up
    runs-on: ubuntu-latest

    steps:
      - name: Hola Setup
        run: echo "Setup"
